# -*- coding: utf-8 -*-
"""410_sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18--dK8gFtzaWItBEU8mb-RYWaTyuivxI
"""

from pprint import pprint
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, HTML

# !pip install praw
import praw

CSS = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(CSS))

user_agent = "Scraper 1.0 by /u/Alternative_Elk2555"
reddit = praw.Reddit(
    client_id = "ggBGWPlZTGbJWFmr0nyiRw",
    client_secret = "vk_rAmVVOihqxWJDo1AnfyHbEEIXvA",
    user_agent = user_agent,
    check_for_async=False
)

headlines_uiuc = set()
for submission in reddit.subreddit('UIUC').hot(limit = None):
  print(submission.title)
  headlines_uiuc.add(submission.title)
print(len(headlines_uiuc))

headlines_chicago = set()
for submission in reddit.subreddit('chicago').hot(limit = None):
  print(submission.title)
  headlines_chicago.add(submission.title)
print(len(headlines_chicago))

df = pd.DataFrame(headlines_uiuc)
df.head()

df2 = pd.DataFrame(headlines_chicago)
df2.head()

display(df)
display(df2)

import nltk
nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer as S

s_uiuc = S()
results_uiuc = []

s_chicago = S()
results_chicago = []

for line in headlines_uiuc:
  polarity = s_uiuc.polarity_scores(line)
  polarity['headline'] = line
  results_uiuc.append(polarity)

for line in headlines_chicago:
  polarity = s_chicago.polarity_scores(line)
  polarity['headline'] = line
  results_chicago.append(polarity)

pprint(results_uiuc[:3], width = 100)
print("\n")
print("\n")
pprint(results_chicago[:3], width = 100)

df = pd.DataFrame.from_records(results_uiuc)
df.head()

df2 = pd.DataFrame.from_records(results_chicago)
df2.head()

display(df)
display(df2)

df['label'] = 'neutral'
df.loc[df['compound'] > 0.2, 'label'] = 'positive'
df.loc[df['compound'] < -0.2, 'label'] = 'negative'
df.head()

df_main = df[['headline', 'label']]
df_main


df2['label'] = 'neutral'
df2.loc[df2['compound'] > 0.2, 'label'] = 'positive'
df2.loc[df2['compound'] < -0.2, 'label'] = 'negative'
df2.head()

df2_main = df2[['headline', 'label']]
df2_main

display(df_main)
display(df2_main)

display(df.label.value_counts(normalize = True) * 100)
print("\n")
display(df2.label.value_counts(normalize = True) * 100)